### ISSUE TITLE
Rechnungssystem kann nicht geöffnet werden

### ISSUE THREAD

**Issue by Priman1c** [Roots-Roleplay/issues#167]
Wenn man als PDler eine Rechnung ausstellen möchte, wird das Overlay nicht geöffnet bzw. angezeigt (zumindest am 29.09 nicht). Drückt man die Taste dafür, wird die Maus sichtbar und man konnte seinen Char nicht mehr bewegen o. Ä., aber das Menü kam nicht. Mit ESC konnte man das anscheinend Ladende (?) Menü schließen und sich wieder normal bewegen.

**Comment by RootsSlumdogE** [comment]
Fixed.
