### ISSUE TITLE
Autokredit wird nicht abgebucht

### ISSUE THREAD

**Issue by schokoblubbcake** [Roots-Roleplay/issues#340]
Das ist wohl ein Thema, das viele gar nicht merken oder ansprechen würden.. :D Bei mir wird der Autokredit nicht abgebucht. Laut Autohaus wird dieser alle 12 Stunden für 6 Tage abgebucht, auf meinem Konto ist allerdings noch genauso viel drauf wie gestern Abend, was weit über 12h her ist. Auch in den Umsätzen bei der Bank ist entsprechend nichts zu sehen.

Nicht, dass ich mich beschweren würde, aber richtig ist das wohl nicht. :D 

Liebe Grüße
Lena / Isabella Ledron

**Comment by Ferguus** [comment]
Die 12 Stunden beziehen sich auf reine Onlinezeit. Also alle 12 Stunden, die du auf dem Server eingeloggt bist wird dir entsprechend eine Rate abgezogen. Falls du noch keine 12 Stunden online warst, ist es tatsächlich korrekt, dass noch keine Rate abgezogen wurde.

**Comment by RootsSlumdogE** [comment]
Korrekt. Nach 12 Stunden Online-Zeit sollte er es abbuchen nich tnach 12 Stunden "echter" Zeit.

**Comment by RootsSlumdogE** [comment]
Kein Bug. **Closed.**
