### ISSUE TITLE
Burner Phone NPC nicht funktinal

### ISSUE THREAD

**Issue by Pulsartorte** [Roots-Roleplay/issues#478]
Schönen Guten abend ich wollte eben bescheid geben das der LSD Burner Typ der kommt wenn man den burner nutzt nicht funktioniert.
![image](https://github.com/user-attachments/assets/63e18bc0-126c-4908-ad12-8075352c4e1f)
![image](https://github.com/user-attachments/assets/de383a2e-1eaf-4a72-bacb-70512c8f913f)

**Comment by RootsSlumdogE** [comment]
Fixed.
